guest_list = ['Jennifer', 'Sofia', 'Eric', 'Carter']
print("This is a list of guests invited to the event:")
print("\t- " + guest_list[0])
print("\t- " + guest_list[1])
print("\t- " + guest_list[2])
print("\t- " + guest_list[3])
print("A larger table is now available. I should invite 3 more guests.")
guest_list.insert(0,'Richard')
guest_list.insert(2,'Elizabeth')
guest_list.append('Ryan')
print("This is the larger list of guests invited to the event:")
print("\t- " + guest_list[0])
print("\t- " + guest_list[1])
print("\t- " + guest_list[2])
print("\t- " + guest_list[3])
print("\t- " + guest_list[4])
print("\t- " + guest_list[5])
print("\t- " + guest_list[6])
print("Due to some issues with the table, only two guests can be invited.")
popped_guests = guest_list.pop()
print("Sorry, you're now uninvited " + popped_guests + ".")
popped_guests = guest_list.pop()
print("Sorry, you're now uninvited " + popped_guests + ".")
popped_guests = guest_list.pop()
print("Sorry, you're now uninvited " + popped_guests + ".")
popped_guests = guest_list.pop()
print("Sorry, you're now uninvited " + popped_guests + ".")
popped_guests = guest_list.pop()
print("Sorry, you're now uninvited " + popped_guests + ".")
print("This is the final list of guests invited to the event:")
print("\t- " + guest_list[0])
print("\t- " + guest_list[1])
del guest_list[0]
del guest_list[0]
print(guest_list)